[package]
name = "djb2_macro"
version = "0.1.0"
edition = "2021"
authors = ["Irate-Walrus"]

[lib]
proc-macro = true

[dependencies]
lazy_static = "1.5.0"
quote = "1.0"
rand = "0.8.5"
syn = { version = "1.0", features = ["full"] }
